### ISSUE TITLE
Exception in thread "ScalaTest-dispatcher" java.lang.NoSuchMethodError: 

### ISSUE THREAD

**Issue by qakart** [reportportal/agent-scala-scalatest#4]
I am trying to incorporate with my scala test framework and getting below error.
we are using our own version of scalatest-maven-plugin 

getting the below error 

Exception in thread "ScalaTest-dispatcher" java.lang.NoSuchMethodError: com.google.common.io.Resources.asByteSource(Ljava/net/URL;)Lcom/google/common/io/ByteSource;
	at com.epam.reportportal.utils.properties.PropertiesLoader.loadProperties(PropertiesLoader.java:91)
	at com.epam.reportportal.utils.properties.PropertiesLoader.access$000(PropertiesLoader.java:44)
	at com.epam.reportportal.utils.properties.PropertiesLoader$1.get(PropertiesLoader.java:55)
	at com.epam.reportportal.utils.properties.PropertiesLoader$1.get(PropertiesLoader.java:51)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:109)
	at com.epam.reportportal.utils.properties.PropertiesLoader.getProperties(PropertiesLoader.java:77)
	at com.epam.reportportal.guice.ReportPortalClientModule.configure(ReportPortalClientModule.java:63)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:229)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:136)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:94)
	at com.google.inject.Guice.createInjector(Guice.java:71)
	at com.google.inject.Guice.createInjector(Guice.java:61)
	at com.epam.reportportal.guice.BaseInjector.<init>(BaseInjector.java:61)
	at com.epam.reportportal.guice.Injector.<init>(Injector.java:60)
	at com.epam.reportportal.guice.Injector.<init>(Injector.java:34)
	at com.epam.reportportal.guice.Injector$1.get(Injector.java:44)
	at com.epam.reportportal.guice.Injector$1.get(Injector.java:40)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:109)
	at com.epam.reportportal.guice.Injector.getInstance(Injector.java:53)
	at com.epam.reportportal.scalatest.RPReporter$$anon$1.get(RPReporter.scala:53)
	at com.epam.reportportal.scalatest.RPReporter$$anon$1.get(RPReporter.scala:52)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:109)
	at com.epam.reportportal.scalatest.RPReporter.apply(RPReporter.scala:77)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.lang.Thread.run(Thread.java:748)

**Comment by HardNorth** [comment]
Abandoned
